### ISSUE TITLE
set_user_info

### ISSUE THREAD

**Issue by thanhpp** [thanhpp/zola#58]
## Request
- token
- username
- description
- avatar (file)
- address
- city
- country
- cover_image
- link (????)

## Response
- code
- message
- data
  - avatar (link)
  - cover_image (link)
  - link (???? - link to user ?)
  - city
  - country

## Test cases
- [x] 1000 | OK
- [x] ErrUnsupportedCountry
- [x] ErrDescriptionTooLong (> 150 chars)

**Comment by thanhpp** [comment]
link: link to a different social network

**Comment by thanhpp** [comment]
- [ ] Người dùng truyền đúng mã phiên đăng nhập, nhưng tham số user_name bị sai định dạng (bị trống hoặc có chứa con số hoặc ký tự đặc biệt khác underscore, hoặc có ký tự đặc biệt ở đầu tiên hoặc quá dài).

**Comment by phamthanhhang208** [comment]
missing name
