### ISSUE TITLE
get_user_friends

### ISSUE THREAD

**Issue by thanhpp** [thanhpp/zola#65]
## Request
- token
- user_id (admin perm)
- index
- count

## response
- code
- message
- data
  - friends
    - user_id
    - user_name
    - avatar
    - status
  - total (number of user's friends)

**Comment by phamthanhhang208** [comment]
index ở đây là gì vậy?

**Comment by thanhpp** [comment]
> index ở đây là gì vậy?

index = page
count = size

**Comment by phamthanhhang208** [comment]
index bắt đầu từ 0 hay 1
