### ISSUE TITLE
Bugs list

### ISSUE THREAD

**Issue by phamthanhhang208** [thanhpp/zola#91]
- [x] set user info - validation for username and name
- [x] get comment - return empty even with friend relation ( adminzola and Admin )
- [x] count default = 20

**Comment by phamthanhhang208** [comment]
- [ ] get comment not return unix time

**Comment by phamthanhhang208** [comment]
- [ ] del comment always return invalid post id

**Comment by phamthanhhang208** [comment]
- [ ] get post and get list post inconsistency with name and username

**Comment by thanhpp** [comment]
The username validation should not be changed due to the specified requirement.
The name validation now accept: numbers, letters and '_' (the first character is not acceptable if it is '_')
